version: '3'
services:
    db:
         image: mysql:5.7.22
         volumes:
           - ./db_data:/var/lib/mysql
         restart: always
         container_name: vlct_mysql
         hostname: vlct_mysql
         networks:
            - spring-mysql
         environment:
           MYSQL_ROOT_PASSWORD: mypassword
           MYSQL_DATABASE: vlct
           MYSQL_USER: vlct
           MYSQL_PASSWORD: mypassword
         ports:
            - 3306:3306
    vlct-app:
        depends_on:
           - db
        container_name: vlct
        build:
          context: .
          dockerfile: Dockerfile
          args:
            JAR_FILE: ${JAR_FILE}
        networks: 
            - spring-mysql
        environment:
              SPRING_DATASOURCE_URL: jdbc:mysql://db/vlct
              SPRING_DATASOURCE_USERNAME: root
              SPRING_DATASOURCE_PASSWORD: mypassword
              SPRING_PROFILES_ACTIVE: prod,swagger
        ports:
            - 9090:8080
        #stdin_open: true
        #tty: true
networks:
    spring-mysql:
volumes:
  db-data:        